# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ebiz-kg-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io//
        username: ${{ secrets.AzureAppService_ContainerUsername_fff9deca233c409a96e72540263148be }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e9ebb5c7b7b448168d6da3e860988788 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io//${{ secrets.AzureAppService_ContainerUsername_fff9deca233c409a96e72540263148be }}/ebiznes2022:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ebiz-kg-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0561e9e3cca74ee8855078f813938c85 }}
        images: 'ghcr.io//${{ secrets.AzureAppService_ContainerUsername_fff9deca233c409a96e72540263148be }}/ebiznes2022:${{ github.sha }}'