# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ebiz-kg-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d1e622eda39844649b9f20b8e262fe0b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_216a6f1f20d341c0947ba2b7f3397fad }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d1e622eda39844649b9f20b8e262fe0b }}/ebiznes2022:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ebiz-kg-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d1230b8b6133464d96fd6ae89e85213e }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d1e622eda39844649b9f20b8e262fe0b }}/ebiznes2022:${{ github.sha }}'